//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBTransfer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAPilotTest")]
        public string COLLECTION_ID {
            get {
                return ((string)(this["COLLECTION_ID"]));
            }
            set {
                this["COLLECTION_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("topic://sa_test_client")]
        public string CLIENT_TOPIC_QUEUE {
            get {
                return ((string)(this["CLIENT_TOPIC_QUEUE"]));
            }
            set {
                this["CLIENT_TOPIC_QUEUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SATestClient1")]
        public string CLIENT_ID {
            get {
                return ((string)(this["CLIENT_ID"]));
            }
            set {
                this["CLIENT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("queue://sa_pillar_queue")]
        public string PILLAR_QUEUE {
            get {
                return ((string)(this["PILLAR_QUEUE"]));
            }
            set {
                this["PILLAR_QUEUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public string XSD_MIN_VERSION {
            get {
                return ((string)(this["XSD_MIN_VERSION"]));
            }
            set {
                this["XSD_MIN_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public string XSD_VERSION {
            get {
                return ((string)(this["XSD_VERSION"]));
            }
            set {
                this["XSD_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\CollectionSettings.xml")]
        public string COLLECTION_SETTINGS_XSD_FILE_PATH {
            get {
                return ((string)(this["COLLECTION_SETTINGS_XSD_FILE_PATH"]));
            }
            set {
                this["COLLECTION_SETTINGS_XSD_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD5")]
        public string DEFAULT_CHECKSUM_TYPE {
            get {
                return ((string)(this["DEFAULT_CHECKSUM_TYPE"]));
            }
            set {
                this["DEFAULT_CHECKSUM_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\bitrepository-message-xml-24\\xsd\\BitRepositoryMessages.xsd")]
        public string MESSAGE_XSD_FILE_PATH {
            get {
                return ((string)(this["MESSAGE_XSD_FILE_PATH"]));
            }
            set {
                this["MESSAGE_XSD_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("topic://sa-test")]
        public string TOPIC_NAME_DURABLE {
            get {
                return ((string)(this["TOPIC_NAME_DURABLE"]));
            }
            set {
                this["TOPIC_NAME_DURABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pilot Test Broker Network A")]
        public string MESSAGE_BUS_CONFIGURATION_NAME {
            get {
                return ((string)(this["MESSAGE_BUS_CONFIGURATION_NAME"]));
            }
            set {
                this["MESSAGE_BUS_CONFIGURATION_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bitrepository.org/BitRepositoryMessages.xsd")]
        public string XML_NAMESPACE {
            get {
                return ((string)(this["XML_NAMESPACE"]));
            }
            set {
                this["XML_NAMESPACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("topic://SA-GENERAL-TOPIC")]
        public string COLLECTION_DESTINATION {
            get {
                return ((string)(this["COLLECTION_DESTINATION"]));
            }
            set {
                this["COLLECTION_DESTINATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[a-zA-Z_\\.\\-0-9]+$")]
        public string VALID_FILENAME_REGEX {
            get {
                return ((string)(this["VALID_FILENAME_REGEX"]));
            }
            set {
                this["VALID_FILENAME_REGEX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http")]
        public string URI_SCHEME {
            get {
                return ((string)(this["URI_SCHEME"]));
            }
            set {
                this["URI_SCHEME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("queue://sa_test_client")]
        public string CLIENT_QUEUE {
            get {
                return ((string)(this["CLIENT_QUEUE"]));
            }
            set {
                this["CLIENT_QUEUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("failover://(ssl://10.50.32.200:61616?transport.clientcertfilename=D:/client.cer&a" +
            "mp;transport.ClientCertPassword=testen)?initialReconnectDelay=100")]
        public string SSL_BROKER {
            get {
                return ((string)(this["SSL_BROKER"]));
            }
            set {
                this["SSL_BROKER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MAX_EXECUTING_ITEMS {
            get {
                return ((int)(this["MAX_EXECUTING_ITEMS"]));
            }
            set {
                this["MAX_EXECUTING_ITEMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ssl://10.50.32.200:61616?transport.clientcertfilename=C:/Downloads/Apache/apache-" +
            "activemq-5.5.1/conf/broker_cert.cer")]
        public string COMMON_QUEUE {
            get {
                return ((string)(this["COMMON_QUEUE"]));
            }
            set {
                this["COMMON_QUEUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120000")]
        public double IdentificationTimeout {
            get {
                return ((double)(this["IdentificationTimeout"]));
            }
            set {
                this["IdentificationTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120000")]
        public double OperationTimeout {
            get {
                return ((double)(this["OperationTimeout"]));
            }
            set {
                this["OperationTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MAX_NUMBER_OF_REQUEST_RETRIES {
            get {
                return ((int)(this["MAX_NUMBER_OF_REQUEST_RETRIES"]));
            }
            set {
                this["MAX_NUMBER_OF_REQUEST_RETRIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>SBTape1</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PILLAR_IDS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PILLAR_IDS"]));
            }
            set {
                this["PILLAR_IDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>80</string>\r\n  <string>8080</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PORT_RANGE {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PORT_RANGE"]));
            }
            set {
                this["PORT_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CHECKSUMPILLAR_IDS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CHECKSUMPILLAR_IDS"]));
            }
            set {
                this["CHECKSUMPILLAR_IDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int TIME_TO_WAIT_AFTER_TIMEOUT {
            get {
                return ((int)(this["TIME_TO_WAIT_AFTER_TIMEOUT"]));
            }
            set {
                this["TIME_TO_WAIT_AFTER_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ADDRESS_FOR_FILE_TRANSFER {
            get {
                return ((string)(this["ADDRESS_FOR_FILE_TRANSFER"]));
            }
            set {
                this["ADDRESS_FOR_FILE_TRANSFER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\SB.txt")]
        public string SessionTypePath {
            get {
                return ((string)(this["SessionTypePath"]));
            }
            set {
                this["SessionTypePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\SBTemp")]
        public string TempFilePath {
            get {
                return ((string)(this["TempFilePath"]));
            }
            set {
                this["TempFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\NewLogs")]
        public string NewLogPath {
            get {
                return ((string)(this["NewLogPath"]));
            }
            set {
                this["NewLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\OldLogs")]
        public string OldLogPath {
            get {
                return ((string)(this["OldLogPath"]));
            }
            set {
                this["OldLogPath"] = value;
            }
        }
    }
}
